version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: AutomationManager.API/Dockerfile
    ports:
      - "5200:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=AutomationManager;Username=postgres;Password=password
      # - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

  web:
    build:
      context: .
      dockerfile: AutomationManager.Web/Dockerfile
    ports:
      - "5201:8080"
    environment:
      - "ApiBaseUrl=http://api:8080"
      # - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - web_dataprotection_keys:/app/keys

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=AutomationManager
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  web_dataprotection_keys: